export default {
    products : [
        {
        _id:1,
        name:"Tiles",
        category:"Tiles",
        image:"/images/tiles.jpg",
        brand:"X",
        price:40,
        rating:4.5,
        numReviews:10,
        countInStock:5
    },
    {
        _id:2,
        name:"Electricals",
        category:"Electricals",
        image:"/images/electricals.jpeg",
        brand:"Y",
        price:50,
        rating:4.2,
        numReviews:20,
        countInStock:7
    },
    {
        _id:3,
        name:"Pipes",
        category:"Pipes",
        image:"/images/pipes.jpeg",
        brand:"Z",
        price:30,
        rating:4.6,
        numReviews:15,
        countInStock:9
    },
    {
        _id:4,
        name:"Nuts",
        category:"Nuts",
        image:"/images/nuts.jpeg",
        brand:"C",
        price:20,
        rating:4.0,
        numReviews:100,
        countInStock:2
    },
    {
        _id:5,    
        name:"Paints",
        category:"Paints",
        image:"/images/paints.jpeg",
        brand:"A",
        price:45,
        rating:3.5,
        numReviews:110,
        countInStock:3
    },
    {
        _id:6,
        name:"Tiles",
        category:"Tiles",
        image:"/images/tiles.jpg",
        brand:"X",
        price:80,
        rating:4.8,
        numReviews:50,
        countInStock:4
    },
    {
        _id:7,
        name:"Electricals",
        category:"Electricals",
        image:"/images/electricals.jpeg",
        brand:"Y",
        price:100,
        rating:2.2,
        numReviews:200,
        countInStock:0
    }
    ]
    }